# Generated by Django 3.2.7 on 2021-09-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_schema_string_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[('comma', 'Comma (,)'), ('semicolon', 'Semicolon(;)'), ('dash', 'Dash(-)')], default='comma', max_length=10),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[('double', 'Double-quote(")'), ('single', "Single-quote(')")], default='double', max_length=10),
        ),
    ]
